# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StatisticsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticsWidget(object):
    def setupUi(self, StatisticsWidget):
        StatisticsWidget.setObjectName("StatisticsWidget")
        StatisticsWidget.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(StatisticsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_view_mode = QtWidgets.QComboBox(StatisticsWidget)
        self.comboBox_view_mode.setObjectName("comboBox_view_mode")
        self.comboBox_view_mode.addItem("")
        self.comboBox_view_mode.addItem("")
        self.comboBox_view_mode.addItem("")
        self.comboBox_view_mode.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_view_mode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.GraphicLayout = QtWidgets.QHBoxLayout()
        self.GraphicLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.GraphicLayout.setObjectName("GraphicLayout")
        self.verticalLayout.addLayout(self.GraphicLayout)

        self.retranslateUi(StatisticsWidget)
        QtCore.QMetaObject.connectSlotsByName(StatisticsWidget)

    def retranslateUi(self, StatisticsWidget):
        _translate = QtCore.QCoreApplication.translate
        StatisticsWidget.setWindowTitle(_translate("StatisticsWidget", "历史使用统计"))
        self.comboBox_view_mode.setItemText(0, _translate("StatisticsWidget", "日视图"))
        self.comboBox_view_mode.setItemText(1, _translate("StatisticsWidget", "周视图"))
        self.comboBox_view_mode.setItemText(2, _translate("StatisticsWidget", "月视图"))
        self.comboBox_view_mode.setItemText(3, _translate("StatisticsWidget", "年视图"))
